services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: polynexus_frontend
    ports:
      - "7771:7771"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://13.235.143.251:7770
